apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rag-pipeline-role
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
